version: "3.9"

services:
  # Сервер с EJB
  payara-ejb:
    image: payara/server-full:5.2022.5-jdk11
    container_name: payara-ejb
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "4849:4848"
    volumes:
      - ./deployments/ejb:/opt/payara/deployments
      - ./deployments/ejb/post-boot.asadmin:/opt/payara/config/post-boot-commands.asadmin
    networks:
      - ejb-net

  # Сервер с Web клиентом
  payara-web:
    image: payara/server-full:5.2022.5-jdk11
    container_name: payara-web
    restart: unless-stopped
    ports:
      - "8082:8080"
      - "4850:4848"
    depends_on:
      - payara-ejb
    volumes:
      - ./deployments/web:/opt/payara/deployments
    networks:
      - ejb-net

networks:
  ejb-net:
    driver: bridge